name: PHP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check PHP Version & Composer Validation
        run: php --version && composer validate

      - name: Testing PHPUnit
        run: composer run-script test

      - name: Secret Key
        run: php -r "echo ${{ SECRET_KEY }};"
